language: node_js

node_js:
  - 9.8.0

sudo: required

env:
  global:

cache:
  directories:
    - node_modules
    - "$HOME/.ipfs"

before_cache:
  - rm -rf $HOME/.ipfs/repo.lock
  - rm -rf $HOME/.ipfs/api

install:
  - npm i

script:
  - npm test

after_success:
  - npm run preview && bash ./scripts/gh_deploy.sh
  - git show-ref
  - git remote show origin
  - npm deploy