language: node_js

node_js:
  - 9.8.0

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
    - node_modules
    - "$HOME/.ipfs"

before_cache:
  - rm -rf $HOME/.ipfs/repo.lock
  - rm -rf $HOME/.ipfs/api

before_install:
  - curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash

before_script:
  - mkdir $HOME/.ipfs/keystore/
  - echo $IPFS_KEY | openssl base64 -d -out $HOME/.ipfs/keystore/decentracord

script:
  - npm test
  - npm run deploy

after_success:
  - fossa test