language: node_js

node_js:
  - 9.8.0

sudo: required

env:
  global:

cache:
  directories:
    - node_modules
    - "$HOME/.ipfs"

before_cache:
  - rm -rf $HOME/.ipfs/repo.lock
  - rm -rf $HOME/.ipfs/api

script:
  - npm test
  - npm run deploy
