language: node_js

node_js:
  - 9.8.0

sudo: required

env:
  global:

cache:
  directories:
    - node_modules
    - "$HOME/.ipfs"

before_cache:
  - rm -rf $HOME/.ipfs/repo.lock
  - rm -rf $HOME/.ipfs/api

install:
  - npm i

before_script:
  - git remote set-url origin https://lukas2005:${GH_TOKEN}@github.com/Anchor-Chat/Anchor-Web.git

script:
  - npm test

after_success:
  - npm run preview && bash ./scripts/gh_deploy.sh
  - npm deploy